yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    # Информация об авторе
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    # Информация о технологиях
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Группа
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл
    path('profile/<str:username>/', views.profile, name='profile'),
    # Редактирование поста
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    # Пост
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Создание поста
    path('create/', views.post_create, name='post_create'),
    # Главная страница
    path('', views.index, name='index'),
    # Комментарий к посту
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'
    ),
    # Подписки
    path('follow/', views.follow_index, name='follow_index'),
    # Подписка на автора
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    # Отписка от автора
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    import debug_toolbar
    urlpatterns += (
        path(
            '__debug__/',
            include(debug_toolbar.urls)
        ),
    )

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Game</span>tube</p>    
</footer>

yatube/templates/includes/form.html
{% load user_filters %}
{% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}            
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
{% endif %}
<form method="post" {% if action_url %} action="{% url action_url %}" {% endif %}>
  {% csrf_token %}
  {% for field in form %}<div class="form-group row my-3"
    {% if field.field.required %} 
      aria-required="true"
    {% else %}
      aria-required="false"
    {% endif %}
  >
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
        {% if field.field.required %}
          <span class="required text-danger">*</span>
        {% endif %}
    </label>
    <div>
    {{ field|addclass:'form-control' }}
      {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
      {% endif %}
    </div>
  </div>
{% endfor %}

yatube/templates/includes/header.html
{% load static %}
  <nav class="navbar navbar-light" style="background-color: orange">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Game</span>tube
      </a>
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}"
              href="{% url 'about:author' %}">
              <span style="color:#e80000"><b>Об авторе</b></span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}"
              href="{% url 'about:tech' %}">
              <span style="color:#e80000"><b>Технологии</b></span>
            </a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}"
                 href="{% url 'posts:post_create' %}"><span style="color:#e80000"><b>Новая запись</b></a></span>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light {% if view_name == 'users:password_change' %}active{% endif %}"
                 href="{% url 'users:password_change' %}"><span style="color:black">Изменить пароль</a></span>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light {% if view_name == 'users:logout' %}active{% endif %}"
                 href="{% url 'users:logout' %}"><span style="color:black">Выйти</a></span>
            </li>
            <li>Пользователь: {{ user.username }}</li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link link-light {% if view_name == 'users:login' %}active{% endif %}"
                 href="{% url 'users:login' %}"><span style="color:black">Войти</a></span>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light {% if view_name == 'users:signup' %}active{% endif %}"
                 href="{% url 'users:signup' %}"><span style="color:black">Регистрация</a></span>
            </li>
          {% endif %}
        {% endwith %}
      </ul>
    </div>
  </nav>