yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    # Информация об авторе
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    # Информация о технологиях
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Группа
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл
    path('profile/<str:username>/', views.profile, name='profile'),
    # Редактирование поста
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    # Пост
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Создание поста
    path('create/', views.post_create, name='post_create'),
    # Главная страница
    path('', views.index, name='index'),
    # Комментарий к посту
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'
    ),
    # Подписки
    path('follow/', views.follow_index, name='follow_index'),
    # Подписка на автора
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    # Отписка от автора
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    import debug_toolbar
    urlpatterns += (
        path(
            '__debug__/',
            include(debug_toolbar.urls)
        ),
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """Модель для группы."""
    title = models.CharField(
        verbose_name='Название',
        max_length=200
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='URL'
    )
    description = models.TextField(
        verbose_name='Описание'
    )

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    """Модель для поста."""
    text = models.TextField(
        verbose_name='Текст',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    """Модель для комментария."""
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='comments'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    """Модель для подписки."""
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follow'
            )
        ]
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self):
        return f'{self.user} подписался на {self.author}'

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Post, Comment


class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = (
            'text',
            'group',
            'image'
        )
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа нового поста',
            'image': 'Новое изображение',
        }
        labels = {
            'text': 'Текст поста',
            'image': 'Картинка',
        }


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ['text']
        help_texts = {
            'text': 'Напишите комментарий',
        }
        labes = {
            'text': 'Текст комментария',
        }

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import PostForm, CommentForm
from .models import Post, Group, Follow, User

User = get_user_model()


LIMIT = 10


def get_paginator(posts, request):
    """Пагинация."""
    paginator = Paginator(posts, LIMIT)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


@cache_page(20)
def index(request):
    """Главная страница."""
    post_list = Post.objects.select_related('author', 'group')
    page_obj = get_paginator(post_list, request)
    template = 'posts/index.html'
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    """Страница с постами, отсортированными по группам."""
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group)
    page_obj = get_paginator(post_list, request)
    template = 'posts/group_list.html'
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    """Профайл пользователя."""
    author = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author=author)
    page_obj = get_paginator(post_list, request)
    template = 'posts/profile.html'
    following = False
    if request.user.is_authenticated and author != request.user:
        following = Follow.objects.filter(
            user=request.user,
            author=author
        ).exists()
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    """Страница поста."""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    template = 'posts/post_detail.html'
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    """Создание поста."""
    form = PostForm(request.POST or None)
    if not form.is_valid():
        template = 'posts/create_post.html'
        context = {
            'form': form,
        }
        return render(request, template, context)

    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect(
        'posts:profile',
        username=post.author.username
    )


@login_required
def post_edit(request, post_id):
    """Редактирование поста."""
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect(
            'posts:post_detail',
            post_id=post_id
        )

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if not form.is_valid():
        context = {
            'form': form,
            'post_id': post_id,
            'is_edit': True,
        }
        return render(
            request,
            'posts/create_post.html',
            context
        )
    form.save()
    return redirect(
        'posts:post_detail',
        post_id=post_id
    )


@login_required
def add_comment(request, post_id):
    """Добавление комментария."""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect(
        'posts:post_detail',
        post_id=post_id
    )


@login_required
def follow_index(request):
    """Информация о текущем пользователе."""
    post_list = Post.objects.filter(
        author__following__user=request.user)
    page_obj = get_paginator(post_list, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Подписка на автора."""
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    """Отписка от автора."""
    author = User.objects.get(username=username)
    user_follower = get_object_or_404(
        Follow,
        user=request.user,
        author=author
    )
    user_follower.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}    
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Новая запись
  {% endif %}
{% endblock %}

{% block content %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                  Новая запись
                {% endif %}>
              </div>
              <div class="card-body">
              {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %} 
                    <div class="alert alert-danger"> 
                      {{ error|escape }} 
                    </div> 
                  {% endfor %} 
                {% endif %}
                <form method="post" enctype="multipart/form-data"
                {% if is_edit %}
                  action="{% url 'posts:post_edit' form.instance.id %}"
                {% else %}
                  action="{% url 'posts:post_create' %}
                {% endif %}">
                {% csrf_token %}
                  {% for field in form %}
                  <div class="form-group row my-3 "
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  <div>
                    {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small
                          id="{{ field.id_for_label }}-help"
                          class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                  </div>
                </div>
                {% endfor %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить запись
                      {% endif %}
                    </button>
                  </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
    </main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Избранные авторы
{% endblock %}
{% block content %}
{% load cache %}
{% cache 20 sidebar %}
  {% include 'posts/includes/switcher.html' with follow=True %}
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaksbr }}</p>
    <p>
    <a href="{% url 'posts:post_detail' post.pk %}">Подробная информация </a>
    </p>
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">
      Все записи группы
    </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
  {% endcache %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %} 
{% load thumbnail %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}

{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description|linebreaks }}<p>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{post.author.get_full_name}} 
          <a href="{% url 'posts:profile' post.author.username %}">
          все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img-top" src="{{ im.url }}">
      {% endthumbnail %}      
      <p>{{ post.text|linebreaksbr }}</p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a><br>
      </article>
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    <div class="d-flex justify-content-center">
      <div>
        {% include 'posts/includes/paginator.html' %}
      </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
{% load cache %}
{% cache 20 index_page %}

  {% include 'posts/includes/switcher.html' with index=True %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {% if post.author.get_full_name %}
              {{ post.author.get_full_name }}
            {% else %}
              {{ post.author }}
            {% endif %} 
            <a href="{% url 'posts:profile' post.author %}">
              все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:'d E Y' }}
          </li>
        </ul>
        {% thumbnail post.image "1920x1080" crop="center" upscale=True as im %}
          <img class="card-img-top" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text|linebreaksbr }}</p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a><br>
      </article>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи дневника</a>
      {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    <div class="d-flex justify-content-center">
      <div>
        {% include 'posts/includes/paginator.html' %}
    </div>
  </div>
{% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}    
  {{ post.text|truncatewords:30}}
{% endblock %}
{% block content %}
  <main>
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }} 
          </li>
            <li class="list-group-item">
              {% if post.group %}
              Группа: {{ post.group.title }}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи дневника
              </a>
            {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: {{ post.author.posts.count }}
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя
              </a>
            </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">

      <div class="card bg-light" style="width: 100%">
        {% thumbnail post.image "1920x1080" crop="center" upscale=True as im %}
          <img class="card-img-top" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaksbr}}
        </p>
        {% if user == post.author %}
          <div class="btn-group">
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post_id=post.id %}" role="button">
            редактировать запись
          </a>
        {% endif %}
      </article>
    </div>
    
    {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
          <form method="post" action="{% url 'posts:add_comment' post.id %}">
            {% csrf_token %}      
            <div class="form-group mb-2">
              {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      </div>
    {% endif %}

    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.username }}
            </a>
          </h5>
          <p>
            {{ comment.text }}
          </p>
        </div>
      </div>
    {% endfor %} 
  </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
  {% block title %}    
    Профайл пользователя {{ author.get_full_name }}
  {% endblock %}

{% block content %}
  <main>
    <div class="container py-5">  
      <div class="mb-5">      
        <h1>Все посты пользователя {{ author.get_full_name }}</h1>
        <h3>Всего постов: {{ page_obj.paginator.count }} </h3>
        {% if request.user.is_authenticated and author != request.user %}
        {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
        {% else %}
        
        <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
        </a>
        {% endif %}
        {% endif %}
      </div>
    </div>
        {% for post in page_obj %}  
        <article>
          <ul>
            <li>
              Автор: {{ author.get_full_name }}
              <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img-top" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text|linebreaksbr }}
          </p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
        </article>
        {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи дневника</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
      </div>
    </main>
    {% endblock %}